server:
  port: ${SERVER_PORT:8080}
spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:192.168.8.202}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:Tyfo@2023}